In [1]:
import pandas as pd
import numpy as np

# SERIES

In [2]:
labels = ['a' , 'b' , 'c']
lists = [10 , 20 , 30]
arr = np.array([10 , 20 , 30])
d = {1 : 10 , 2 : 20 , 3 : 30}
pd.Series(lists)

0    10
1    20
2    30
dtype: int64

In [3]:
pd.Series(lists , labels)

a    10
b    20
c    30
dtype: int64

In [4]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [5]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

# DATAFRAMES

## Creating Dataframe

In [6]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
print(df)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [7]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [8]:
columns = ["Name" , "Age" , "City" , "Salary"]
df2 = pd.DataFrame(data_list , columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

# SELECTION AND INDEXING

In [9]:
df2[["Name" , "City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [10]:
# CREATING A NEW COLUMN
df2["Designation"] = ["Doctor" , "Engineer" , "Doctor" , "Pilot"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000       Pilot

In [11]:
df2.drop("Designation" , axis = 1 , inplace = True) #Without inplace it will only show temporarily how the data will look like!

In [12]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

SELECTING A ROW

In [13]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [14]:
df2.loc[[0 , 1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [15]:
df2.iloc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

SELECTING SUBSET

In [16]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [17]:
df.loc[[0 , 1]][["City" , "Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [18]:
df.loc[[2 , 3]][["Name" , "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

CONDITIONAL SELECTION

In [19]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [20]:
#Age > 30
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [21]:
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

# Missing Data

In [22]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df3 = pd.DataFrame(data)
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [23]:
df3.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [24]:
df3.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [25]:
df3.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

REMOVING MISSING DATA

In [26]:
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [27]:
df3.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [28]:
df3.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

FILLING THE MISSING DATA

In [29]:
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [30]:
df3.fillna(value=0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [31]:
values = {'A' : 0 , 'B' : 100 , 'C' : 300 , 'D' : 400}
df3.fillna(value = values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [32]:
df3.fillna(df3.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

# MERGING JOINING CONCATENATION

Merging 2 Dataframe

In [33]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [34]:
print(employees)
salaries

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [35]:
pd.merge(employees , salaries , on='employee_id' , how="outer")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

CONCATENATION OF DATAFRAMES

In [36]:
df4 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df5 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [37]:
df4

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [38]:
df5

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [39]:
pd.concat([df4 , df5])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [40]:
pd.concat([df4 , df5] , axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

JOINING

In [41]:
df6 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

df7 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [42]:
df6

      name
1    Alice
2      Bob
3  Charlie

In [43]:
df7

   score
2     85
3     90
4     75

In [44]:
df6.join(df7 , how="outer")

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

# GROUP BY AND AGGREGATION

GROUP BY

In [45]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df8 = pd.DataFrame(data)

In [46]:
df8

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [47]:
cat = df8.groupby('Category')
for i , v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [48]:
cat = df8.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [49]:
cat = df8.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [50]:
cat = df8.groupby(['Category' , 'Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

Aggregation

In [51]:
df8['Sales'].mean()

187.5

In [52]:
df8['Sales'].agg(['mean' , 'sum' , 'median' , 'min' , 'max'])

mean       187.5
sum       1500.0
median     190.0
min        100.0
max        300.0
Name: Sales, dtype: float64

# PIVOT TABLES

In [53]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}
df9 = pd.DataFrame(data)
df9['Month'] = df9['Date'].dt.month_name()
df9['Quarter'] = 'Q' + df9['Date'].dt.quarter.astype(str)
df9

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    269     72   John  January      Q1
1  2023-01-02       B   West    739     16   Mary  January      Q1
2  2023-01-03       C  North    235     10    Bob  January      Q1
3  2023-01-04       D  South    950     78  Alice  January      Q1
4  2023-01-05       A   East    419     60   John  January      Q1
5  2023-01-06       B   West    401     23   Mary  January      Q1
6  2023-01-07       C  North    737     75    Bob  January      Q1
7  2023-01-08       D  South    490     87  Alice  January      Q1
8  2023-01-09       A   East    774     64   John  January      Q1
9  2023-01-10       B   West    216     28   Mary  January      Q1
10 2023-01-11       C  North    868     61    Bob  January      Q1
11 2023-01-12       D  South    841     22  Alice  January      Q1
12 2023-01-13       A   East    212     63   John  January      Q1
13 2023-01-14       B   West    643     97   Mary  January      Q1
14 2023-01-15       C  North    799     37    Bob  January      Q1
15 2023-01-16       D  South    671     39  Alice  January      Q1
16 2023-01-17       A   East    144     85   John  January      Q1
17 2023-01-18       B   West    787     11   Mary  January      Q1
18 2023-01-19       C  North    418     22    Bob  January      Q1
19 2023-01-20       D  South    509     70  Alice  January      Q1

In [54]:
pd.pivot_table(df9 , values='Sales' , index='Region' , columns='Product' , aggfunc='median')

Product      A      B      C      D
Region
East     269.0    NaN    NaN    NaN
North      NaN    NaN  737.0    NaN
South      NaN    NaN    NaN  671.0
West       NaN  643.0    NaN    NaN

In [55]:
pivot2 = pd.pivot_table(df9, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     363.6    NaN    NaN    NaN  68.8   NaN   NaN   NaN
North      NaN    NaN  611.4    NaN   NaN   NaN  41.0   NaN
South      NaN    NaN    NaN  692.2   NaN   NaN   NaN  59.2
West       NaN  557.2    NaN    NaN   NaN  35.0   NaN   NaN

CrossTab

In [56]:
pd.crosstab(df9['Region'],df9['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# OPERATIONS

In [57]:
df10 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df10

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [58]:
df10.shape

(5, 3)

In [59]:
df10.columns

Index(['A', 'B', 'C'], dtype='object')

In [60]:
df10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [61]:
df10.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [62]:
df10['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

APPLYING SOME FUNC'S

In [63]:
def square(x) : 
    return x ** 2

In [64]:
df10['D'] = df10['B'].apply(square)

In [65]:
df10

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500

In [66]:
df10['E'] = df10['B'].apply(lambda x : x ** 2)

In [67]:
df10

   A   B    C     D     E
0  1  10  100   100   100
1  2  20  200   400   400
2  3  30  300   900   900
3  4  40  400  1600  1600
4  5  50  500  2500  2500