In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
X = df.drop("species" , axis = 1)
y = df['species']

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [8]:
#KNN
from sklearn.neighbors import KNeighborsClassifier

In [9]:
model_knn = KNeighborsClassifier(n_neighbors = 13)

In [10]:
model_knn.fit(X_train , y_train)

KNeighborsClassifier(n_neighbors=13)

In [11]:
model_knn.score(X_test , y_test)

1.0

#Overfitting when the accuracy is above 95%

In [12]:
#SVM
from sklearn.svm import SVC

In [13]:
model_svm = SVC(gamma = 'auto')
model_svm.fit(X_train, y_train)
model_svm.score(X_test , y_test)

1.0

# ON CHANGING DIFFERENT PARAMETERS OF MODELS WE ARE GETTING DIFFERENT SCORES. SO NOW LET'S TRY HYPERPARAMETER TUNING

# Grid Search CV

In [14]:
from sklearn.model_selection import GridSearchCV

In [15]:
classifier = GridSearchCV((model_svm) , {
    'C' : [1 , 10 , 20 , 30],
    'kernel' : ['rbf' , 'linear']
} , cv = 5 , return_train_score=False)

In [16]:
classifier.fit(X , y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [17]:
results = pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007330,0.003441,0.001952,0.001649,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002819,0.003042,0.004148,0.004801,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.003064,0.002935,0.003805,0.002462,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.004219,0.003644,0.001812,0.003624,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.003021,0.006043,0.000000,0.000000,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.003019,0.002700,0.005525,0.005205,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002820,0.000753,0.002488,0.000955,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.003082,0.006165,0.000829,0.001657,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [18]:
results[['param_C' , 'param_kernel' , 'mean_test_score']]

  param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667
6      30          rbf         0.960000
7      30       linear         0.960000

# RANDOM SEARCH CV

In [19]:
from sklearn.model_selection import RandomizedSearchCV

In [20]:
classifier_r = RandomizedSearchCV((model_svm) , {
    'C' : [1 , 10 , 20 , 30],
    'kernel' : ['rbf' , 'linear']
} , n_iter = 4 , cv = 5 , return_train_score=False)

In [21]:
classifier_r.fit(X , y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [22]:
results = pd.DataFrame(classifier_r.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007776,0.002542,0.001822,0.002006,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
1,0.002429,0.002284,0.003046,0.004178,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,4
2,0.005565,0.003147,0.002084,0.002636,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.000863,0.001178,0.004329,0.003936,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [23]:
results[['param_C' , 'param_kernel' , 'mean_test_score']]

  param_C param_kernel  mean_test_score
0      20          rbf         0.966667
1      20       linear         0.966667
2       1          rbf         0.980000
3      10          rbf         0.980000